### ISSUE TITLE
打包的时候出错

### ISSUE THREAD

**Issue by lincx** [l-zhi/cherub#2]
打包的时候出错，提示
'rm' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'NODE_ENV' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! lincx-O2h5-boilerplate@1.0.0 build: `rm -rf project/ & NODE_ENV=production webpack --config webpack.config.build.js --progress --colors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lincx-O2h5-boilerplate@1.0.0 build script 'rm -rf project/ & NODE_ENV=production webpack --config webpack.config.build.js --progress --colors'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lincx-O2h5-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -rf project/ & NODE_ENV=production webpack --config webpack.config.build.js --progress --colors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lincx-O2h5-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lincx-O2h5-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\h5\npm-debug.log

请问是哪儿出错了？

**Comment by l-zhi** [comment]
wiindows 下 rm 命令不存在，可以试试删除或者试试v2版本哈
